#!/bin/bash

if [ ! -f "beargit.c" ]; then
  echo "ERROR: Need to run "source init_test" from your source directory"
  return
fi

if [ -d "test" ]; then
  if [ -f "test/.BEARGIT_TEST_IGNORE_ME" ]; then
    rm -r test
  else
    echo "ERROR: A test directory already exists, but it was not created by make. Please manually delete or move this directory and try again."
    return
  fi
fi

make beargit

mkdir test
touch test/.BEARGIT_TEST_IGNORE_ME

if [[ ! "$PATH" =~ "$PWD" ]]; then
  export PATH=$PWD:$PATH
fi

cd test
echo "tttt" >> test1.c
echo "dddd" >> test1.c
echo "" >> test1.c

echo "" >> lkcjsdlkjclskdjdjkkdkdjkldjlkjlkjsldkjlskdjlkjdkjdkjlsjdklsjdlk
echo "hh" >> lkcjsdlkjclskdjdjkkdkdjkldjlkjlkjsldkjlskdjlkjdkjdkjlsjdklsjdlk

beargit init

beargit add test1.c
beargit add lkcjsdlkjclskdjdjkkdkdjkldjlkjlkjsldkjlskdjlkjdkjdkjlsjdklsjdlk

beargit status

beargit commit -m "djijijijijiGO BEARs!"
beargit commit -m "GO BEARS!"

beargit commit -m " wewwewddfdgobearsGO BEARSd!GO BEARS! "

beargit rm test1.c

beargit commit -m "GGGO BEARS!h"

beargit rm lkcjsdlkjclskdjdjkkdkdjkldjlkjlkjsldkjlskdjlkjdkjdkjlsjdklsjdlk

beargit commit -m "GO BEARS!"

beargit log
